use std::fmt;
use std::fmt::Write;
use interconnect::Interconnect;
use strfmt::{self, strfmt_map};

#[derive(Clone, Copy)]
struct OpcodeSpec {
    opcode_disasm: &'static str,
    opcode_length: u16,
}

#[derive(Clone, Copy)]
pub struct Opcode {
    opcode_disasm: &'static str,
    pub opcode_length: u16,

    opcode_addr: u16,
    opcode_n0: u8,
    opcode_n1: u8,
}

impl fmt::Display for Opcode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f,
               "{}",
               strfmt_map(self.opcode_disasm,
                          &|mut fmt: strfmt::Formatter| {
            match fmt.key {
                "0" => fmt.write_str(&format!("{:02X}", self.opcode_n0)).unwrap(),
                "1" => fmt.write_str(&format!("{:02X}", self.opcode_n1)).unwrap(),
                "2" => fmt.write_str(&format!("{:04X}", self.opcode_addr)).unwrap(),
                _ => unreachable!(),
            }
            Ok(())
        })
        .unwrap())?;

        Ok(())
    }
}

#[cfg_attr(rustfmt, rustfmt_skip)]
const OPCODES: [OpcodeSpec; 256] = [
    OpcodeSpec { opcode_disasm: "NOP", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD BC, 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "LD (BC), A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC BC", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC B", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC B", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD B, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RCLA", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (0x{1}{0}), SP", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "ADD HL, BC", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, (BC)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC BC", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD C 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RRCA", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "STOP", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD DE, 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "LD (DE), A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC DE", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC D", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC D", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD D, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RLA", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "JR 0x{0} (=> 0x{2})", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "ADD HL, DE", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, (DE)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC DE", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC E", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC E", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD E, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RRA", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "JR NZ, 0x{0} (=> 0x{2})", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "LD HL, 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "LDI (HL), A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC HL", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC H", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC H", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD H, {0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "DAA", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "JR Z, 0x{0} (=> 0x{2})", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "ADD HL, HL", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LDI A, (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC HL", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC L", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC L", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD L, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "CPL", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "JR NC, 0x{0} (-> 0x{2})", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "LD SP, (0x{1}{0})", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "LDD (HL), A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC SP", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (HL), 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SCF", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "JR C, 0x{0} (=> 0x{2})", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "ADD HL, SP", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LDD A, (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC SP", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "INC A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DEC A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "CCF", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD B, B", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD B, C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD B, D", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD B, E", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD B, H", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD B, L", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD B, (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD B, A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD C, B", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD C, C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD C, D", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD C, E", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD C, H", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD C, L", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD C, (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD C, A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD D, B", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD D, C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD D, D", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD D, E", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD D, H", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD D, L", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD D, (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD D, A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD E, B", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD E, C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD E, D", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD E, E", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD E, H", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD E, L", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD E, (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD E, A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD H, B", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD H, C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD H, D", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD H, E", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD H, H", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD H, L", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD H, (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD H, A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD L, B", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD L, C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD L, D", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD L, E", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD L, H", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD L, L", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD L, (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD L, A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (HL), B", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (HL), C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (HL), D", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (HL), E", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (HL), H", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (HL), L", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "HALT", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (HL), A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, B", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, D", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, E", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, H", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, L", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, A", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "ADD A,B", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADD A,C", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADD A,D", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADD A,E", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADD A,H", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADD A,L", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADD A,(HL)", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADD A,A", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADC A,B", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADC A,C", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADC A,D", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADC A,E", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADC A,H", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADC A,L", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADC A,(HL)", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "ADC A,A", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SUB B", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SUB C", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SUB D", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SUB E", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SUB H", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SUB L", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SUB (HL)", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SUB A", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SBC A,B", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SBC A,C", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SBC A,D", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SBC A,E", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SBC A,H", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SBC A,L", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SBC A,(HL)", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "SBC A,A", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "AND B", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "AND C", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "AND D", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "AND E", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "AND H", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "AND L", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "AND (HL)", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "AND A", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "XOR B", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "XOR C", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "XOR D", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "XOR E", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "XOR H", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "XOR L", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "XOR (HL)", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "XOR A", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "OR B", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "OR C", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "OR D", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "OR E", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "OR H", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "OR L", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "OR (HL)", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "OR A", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "CP B", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "CP C", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "CP D", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "CP E", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "CP H", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "CP L", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "CP (HL)", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "CP A", opcode_length: 1},
    OpcodeSpec { opcode_disasm: "RET NZ", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "POP BC", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "JP NZ, 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "JP 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "CALL NZ, 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "PUSH BC", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "ADD A, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RST 0x00", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "RET Z", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "RET", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "JP Z 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // 0xcb - extended instruction prefix
    OpcodeSpec { opcode_disasm: "CALL Z 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "CALL 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "ADC A, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RST 0x08", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "RET NC", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "POP DE", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "JP NC 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // D3 - illegal op
    OpcodeSpec { opcode_disasm: "CALL NC 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "PUSH DE", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "SUB A, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RST 0x10", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "RET C", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "RETI", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "JP C 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // DB - illegal op
    OpcodeSpec { opcode_disasm: "CALL C 0x{1}{0}", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // DD - illegal op
    OpcodeSpec { opcode_disasm: "SBC A, 0x{0}", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "RST 0x18", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (0xff00 0x{0}), A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "POP HL", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (0xFF00 + 0x{0}), A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // E3 - illegal op
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // E4 - illegal op
    OpcodeSpec { opcode_disasm: "PUSH HL", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "AND A, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RST 0x20", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "ADD SP, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "JP (HL)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD (0x{1}{0}), A", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // EB - illegal op
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // EC - illegal op
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // ED - illegal op
    OpcodeSpec { opcode_disasm: "XOR A, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RST 0x28", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, (0xFF00 + 0x{0})", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "POP AF", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, (0xFF00 + C)", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "DI", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // F4 - illegal op
    OpcodeSpec { opcode_disasm: "PUSH AF", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "OR A, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RST 0x30", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD HL, SP", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD SP, HL", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "LD A, (0x{1}{0})", opcode_length: 3 },
    OpcodeSpec { opcode_disasm: "EI", opcode_length: 1 },
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // FC - illegal op
    OpcodeSpec { opcode_disasm: "", opcode_length: 0 }, // FD - illegal op
    OpcodeSpec { opcode_disasm: "CP A, 0x{0}", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RST 0x38", opcode_length: 1 }
];

#[cfg_attr(rustfmt, rustfmt_skip)]
const CBOPCODES: [OpcodeSpec; 256] = [
    OpcodeSpec { opcode_disasm: "RLC B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RLC C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RLC D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RLC E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RLC H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RLC L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RLC (HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RLC A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RRC B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RRC C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RRC D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RRC E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RRC H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RRC L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RRC (HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RRC A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RL B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RL C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RL D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RL E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RL H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RL L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RL (HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RL A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RR B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RR C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RR D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RR E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RR H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RR L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RR (HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RR A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SLA B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SLA C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SLA D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SLA E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SLA H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SLA L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SLA (HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SLA A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRA B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRA C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRA D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRA", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRA H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRA L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRA (HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRA A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SWAP B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SWAP C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SWAP D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SWAP E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SWAP H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SWAP L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SWAP (HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SWAP A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRL B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRL C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRL D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRL E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRL H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRL L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRL (HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SRL A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 0,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 0,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 0,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 0,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 0,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 0,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 0,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 0,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 1,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 1,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 1,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 1,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 1,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 1,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 1,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 1,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 2,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 2,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 2,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 2,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 2,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 2,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 2,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 2,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 3,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 3,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 3,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 3,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 3,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 3,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 3,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 3,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 4,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 4,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 4,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 4,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 4,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 4,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 4,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 4,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 5,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 5,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 5,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 5,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 5,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 5,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 5,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 5,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 6,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 6,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 6,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 6,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 6,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 6,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 6,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 6,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 7,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 7,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 7,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 7,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 7,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 7,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 7,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "BIT 7,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 0,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 0,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 0,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 0,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 0,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 0,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 0,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 0,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 1,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 1,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 1,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 1,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 1,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 1,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 1,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 1,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 2,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 2,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 2,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 2,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 2,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 2,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 2,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 2,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 3,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 3,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 3,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 3,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 3,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 3,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 3,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 3,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 4,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 4,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 4,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 4,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 4,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 4,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 4,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 4,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 5,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 5,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 5,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 5,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 5,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 5,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 5,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 5,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 6,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 6,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 6,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 6,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 6,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 6,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 6,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 6,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 7,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 7,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 7,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 7,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 7,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 7,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 7,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "RES 7,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 0,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 0,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 0,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 0,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 0,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 0,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 0,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 0,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 1,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 1,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 1,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 1,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 1,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 1,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 1,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 1,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 2,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 2,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 2,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 2,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 2,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 2,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 2,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 2,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 3,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 3,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 3,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 3,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 3,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 3,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 3,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 3,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 4,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 4,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 4,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 4,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 4,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 4,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 4,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 4,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 5,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 5,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 5,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 5,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 5,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 5,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 5,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 5,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 6,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 6,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 6,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 6,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 6,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 6,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 6,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 6,A", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 7,B", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 7,C", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 7,D", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 7,E", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 7,H", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 7,L", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 7,(HL)", opcode_length: 2 },
    OpcodeSpec { opcode_disasm: "SET 7,A", opcode_length: 2 },
];

pub fn decode_instr(interconnect: &Interconnect, addr: u16) -> Opcode {
    let instr = interconnect.read_byte(addr);
    let subcode = interconnect.read_byte(addr + 1);
    let mut offset = addr;
    let opcode_spec = if instr == 0xcb {
        offset += 1;
        CBOPCODES[subcode as usize]
    } else {
        OPCODES[instr as usize]
    };

    let n0 = interconnect.read_byte(offset + 1);
    let n1 = interconnect.read_byte(offset + 2);
    let opcode_jr_dest = addr.wrapping_add(n0 as i8 as u16).wrapping_add(opcode_spec.opcode_length as u16);

    if opcode_spec.opcode_disasm == "" {
        panic!("No opcode string for op {0}/{0:02x} ({1}/{1:02x})",
               instr,
               subcode);
    }
    if opcode_spec.opcode_length == 0 {
        panic!("No opcode length for op {0}/{0:02x} ({1}/{1:02x})",
               instr,
               subcode);
    }

    Opcode {
        opcode_disasm: opcode_spec.opcode_disasm,
        opcode_length: opcode_spec.opcode_length,
        opcode_addr: opcode_jr_dest,
        opcode_n0: n0,
        opcode_n1: n1,
    }
}
